version: "3.8"
services:
    nodeserver:
        build:
            context: ./app
        ports:
            - "8081:8081"
            - "8082:8082"
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "80:80"